# site settings

title: Mikail KOCADAĞ
description: Computer Engineering 
taglong: Computer Engineering 
tagshort: MK
url: https://MKLKCDG.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/MKLKCDG/MKLKCDG.github.io

# author settings

author:
  name: Mikail KOCADAĞ
  email: mkocadag219@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: MKLKCDG
  instagram: mikailkocadag
  linkedin: mikailkocadag

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
